server:
  port: 9202
spring:
  application:
    name: story-service-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9200/eureka/
  datasource:
    url: jdbc:mysql://localhost:3306/story?useUnicode=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: indi.wyx0k.story.core.entity
